### ISSUE TITLE
[Question] How to initialize the container once for the entire inference process when using paged caches

### ISSUE THREAD

**Issue by aur61** [NVIDIA/cudnn-frontend#121]
Hi,

I am studying the paged cache with this example, https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/python/52_scaled_dot_product_attention_with_paged_caches.ipynb.

I would like to understand how to initialize a single container with the maximum number of blocks, and update the `container` and `page_table` with the new cache.

One of the possible `container` may look like this: `[max_num_blocks, num_heads, block_size, head_dim]`, then update with the new cache, like this: `container[block_index] = new_k`

As in real inference scenarios, reinitializing the container and `page_table` for every forward pass can be slow.

As noted in the example, the design of the `container` and `paged_table` is left to the user. Could you clarify how cudnn utilizes them to reconstruct the original `value` or `key`?

**Comment by nvmbreughe** [comment]
Hi,

Absolutely, the idea would be to allocate a large enough chunk of memory to fit all of the KV-blocks needed at any given time. In other words, `max_num_blocks` in your container of size `[max_num_blocks, num_heads, block_size, head_dim]` can be made arbitrarily large (up to 2^32-1).  The sample that you are studying is a bit oversimplified where we create a container that is just big enough for the specified sequence size. 

The way cuDNN reconstructs K-cache (V-cache) from K-container + page_table_K (V-container + page_table_V) is as follows:
`Kcache[b,h,s,d]=container[page_table[b,1,s/block_size,1],h,s % block_size,d]`

This is also outlined in the attention documentation in [Attention.md](https://github.com/NVIDIA/cudnn-frontend/blob/main/docs/operations/Attention.md
).

So in practice, whenever you add a new token to the container, say at time stamp T, you will identify a `block_index` where you want to insert it to. If `T % block_size != 0`, it means there already is a block associated with this token and your `page_table` at index `T/block_size` already points to it. You will update `container[page_table[b,1,T/block_size,1],h,T%block_size,d]`  with the newly generated token. When `block_size == 0`, you need to find a new `block_index` in the container as your page table does not point to one yet. This `block_index` into the container points to either a block that has never been used, or an old block of a request that is no longer alive. Then you update your `page_table` at index `T%block_size` to point to the newly identified `block_index`.


Does this help? Please let us know if we can further clarify or if you have sandbox code we can help debug.
