### ISSUE TITLE
Support for half2 type convolution

### ISSUE THREAD

**Issue by infloop777** [NVIDIA/cudnn-frontend#13]
Hi, I'm checking mix precision programming: https://developer.nvidia.com/blog/mixed-precision-programming-cuda-8/ Does cudnn frontend has any support for half2 type convolution?

**Comment by YangXu1990uiuc** [comment]
Hi infloop777, thank you for your questions! Inside the library do have kernels that runs HFMA2 instructions for compute, however in the latest generations of GPUs, the focus has been on tensor cores which is much faster than HFMA2. cuDNN API (include the frontend) hides the implementation details of the actual kernels, so you just need to specify half datatype, and we will dispatch it to the best kernel in the library.

**Comment by infloop777** [comment]
@YangXu1990uiuc Thank you for help!

**Comment by infloop777** [comment]
I have another question regarding to fp16 vs fp32. Do you think for the same convolution fp16 is always better than fp32, or it's worth trying fp32 algorithms as well(though need some graph level modification)?

**Comment by YangXu1990uiuc** [comment]
Hi infloop777, it depends on what's your situation, and what's your definition of better.
1. If your model has high numerical precision requirement, then FP32 will work better for you in terms of convergence and accuracy.
2. If your goal is to achieve good performance but not sacrifice on convergence on most models, then FP16 mixed precision (i.e. FP16 I/O, FP32 compute) will be the better choice.
Of course this also depends on what GPU you are using. Only the newer ones (Volta, Turing, Ampere) can run FP16 mixed precision efficiently.

**Comment by infloop777** [comment]
Thanks! This is helpful.
