### ISSUE TITLE
Cannot build nvidia-tensorflow with v0.5

### ISSUE THREAD

**Issue by ziyuang** [NVIDIA/cudnn-frontend#15]
A Dockerfile to reproduce:

    FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04
    ENV TZ=Europe/London
    RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
    RUN apt-get update && apt-get -y upgrade
    RUN apt-get install -y build-essential git git-lfs wget vim software-properties-common unzip python3-pip
    RUN update-alternatives --install /usr/bin/python python $(which python3) 10
    RUN pip install --upgrade numpy astor
    WORKDIR /workdir
    RUN wget https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-installer-linux-x86_64.sh
    RUN chmod +x bazel-0.26.1-installer-linux-x86_64.sh && ./bazel-0.26.1-installer-linux-x86_64.sh
    
    RUN git clone https://github.com/NVIDIA/cudnn-frontend.git
    RUN git clone --branch r1.15.5+nv21.10 --single-branch https://github.com/NVIDIA/tensorflow.git
    WORKDIR /workdir/tensorflow
    ENV TF_ENABLE_XLA=0 \
        TF_NEED_OPENCL_SYCL=0 \
        TF_NEED_ROCM=0 \
        TF_NEED_CUDA=1 \
        TF_NEED_TENSORRT=0 \
        TF_CUDA_VERSION=11 \
        TF_CUBLAS_VERSION=11 \
        TF_NCCL_VERSION=2 \
        TF_CUDNN_VERSION=8 \
        TF_CUDA_PATHS="/usr/include,/usr/lib/x86_64-linux-gnu,/usr/local/cuda/include,/usr/local/cuda/lib64,/usr/local/cuda/bin,/usr/local/cuda" \
        TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.0,5.2,6.1,7.0,7.5,8.6 \
        CC_OPT_FLAGS="-march=sandybridge -mfma -mfpmath=both -fopenmp"
    RUN PYTHON_BIN_PATH=$(which python) ./configure
    RUN bazel build --config=opt --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka //tensorflow/tools/pip_package:build_pip_package

Error message:

    ERROR: /workdir/tensorflow/tensorflow/stream_executor/cuda/BUILD:343:1: C++ compilation of rule '//tensorflow/stream_executor/cuda:cudnn_plugin' failed (Exit 1)
    In file included from bazel-out/host/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend.h:116,
                     from tensorflow/stream_executor/cuda/cuda_dnn.cc:50:
    bazel-out/host/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend/third_party/cudnn_frontend/include/cudnn_frontend_ExecutionPlanCache.h:29:10: fatal error: cudnn_frontend_OperationGraph.h: No such file or directory
       29 | #include <cudnn_frontend_OperationGraph.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build

while using `git clone --branch v0.4.1 --single-branch https://github.com/NVIDIA/cudnn-frontend.git` seems to work.

**Comment by Anerudhan** [comment]
Hi Ziyuang,
Thanks for the post. 
I see that that `<cudnn_frontend_OperationGraph.h>` file exists in the same directory as the `cudnn_frontend.h`.  
Can you add the  include path while compiling the `cuda_dnn.cc`. Or I can change the "angular braced" inclusion to double quotes.

**Comment by ziyuang** [comment]
> Hi Ziyuang, Thanks for the post. I see that that `<cudnn_frontend_OperationGraph.h>` file exists in the same directory as the `cudnn_frontend.h`. Can you add the include path while compiling the `cuda_dnn.cc`. Or I can change the "angular braced" inclusion to double quotes.

I am not familiar with bazel; I did try adding the include path via `CC_OPT_FLAGS="-I/workdir/cudnn-frontend/include"` and it prompts something like "include path out of the current project".

**Comment by Anerudhan** [comment]
I have updated the v0.5 to point to the commit to SHA 704a61f7a3c16bcc52acfa9c4587b2df7703a29c
Changes are in lines
https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_ExecutionPlanCache.h#L29
https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_ExecutionPlanCache.h#L30

Can you please try the changes. Meanwhile, I will try with your docker repro.

**Comment by ziyuang** [comment]
> I have updated the v0.5 to point to the commit to SHA [704a61f](https://github.com/NVIDIA/cudnn-frontend/commit/704a61f7a3c16bcc52acfa9c4587b2df7703a29c) Changes are in lines https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_ExecutionPlanCache.h#L29 https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_ExecutionPlanCache.h#L30
> 
> Can you please try the changes. Meanwhile, I will try with your docker repro.

It seems to go further, thanks!

**Comment by Anerudhan** [comment]
Thanks @ziyuang . Closing the issue.
