### ISSUE TITLE
Lack of activation function LeakyReLU 

### ISSUE THREAD

**Issue by akineeic** [NVIDIA/cudnn-frontend#18]
Hi,

I’m currently using CUDNN to write a deep learning super-resolution sample. But I found that support for LeakyReLU is not mentioned in the [document](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnActivationMode_t). But LeakyReLU is in my pre-trained model. Could you please give any suggestions or sample code to solve this problem?

Thanks a lot in advance!

**Comment by YangXu1990uiuc** [comment]
Hi @akineeic, you can follow the conv - leaky relu fusion example here
https://github.com/NVIDIA/cudnn-frontend/blob/704a61f7a3c16bcc52acfa9c4587b2df7703a29c/samples/fusion_sample.cpp#L76
If you can let us know your specific use case, we can discuss further how to implement it.

**Comment by akineeic** [comment]
Thanks for your quick reply!  I'm trying to implement [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) with CUDNN APIs to speed up its inference processing. [Here ](https://github.com/xinntao/BasicSR/blob/master/basicsr/archs/rrdbnet_arch.py)is its python version implement code. It is mainly composed of conv，leakyrelu，concat and upsamples. It seems that CUDNN does not have the implementation of the latter three. So I may need to write some CUDA kernel functions to achieve these layers.

**Comment by akineeic** [comment]
The link you provided seems to use your own implemented top-level APIs. So I'm wondering could you please share with me your low-level internal implementation since I’m not familiar with your project. I can spend some time finding and learning the code, so It's okay if you don't have the time.

**Comment by YangXu1990uiuc** [comment]
Thanks for the pointer! We have recently added 2x2 up-sampling support in cuDNN 8.3.1, we will add some examples soon. We don't support concat at this time, but we will look into it!

Regarding the lower level API, I would recommend you to check the code (or step into the code), it's calling cuDNN v8 C API underneath. This project is the official C++ API for cuDNN, it has the same functionality compared to the C backend, but makes things more convenient to use.
e.g. https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_Operation.h
https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_PointWiseDesc.h

**Comment by akineeic** [comment]
This is very helpful to me. Thanks for your patience!

**Comment by YangXu1990uiuc** [comment]
Hi @akineeic hope the responses above answer your questions! I'm closing the issue for now. If you have additional questions, please feel free to open a new issue!
