### ISSUE TITLE
Install CUDNN on NVIDIA Jetson AGX conda environment

### ISSUE THREAD

**Issue by sivashankar28** [NVIDIA/cudnn-frontend#19]
Hi I am trying to install CUDNN on my AGX conda environment. 
I have a cuda version 10.2.89.

Is someone able to help guide me through this

**Comment by Anerudhan** [comment]
Hi @sivashankar28 ,

You can grab the latest cuDNN debian/tarballs from [https://developer.nvidia.com/rdp/cudnn-download](https://developer.nvidia.com/rdp/cudnn-download) and selecting the appropriate CUDA version in your environment.

Thanks

**Comment by Anerudhan** [comment]
Closing this issue for now. Please reopen if necessary.

Thanks,
Anerudhan
obo cuDNN Team
