### ISSUE TITLE
how to map to the original algorithm

### ISSUE THREAD

**Issue by jackmsye** [NVIDIA/cudnn-frontend#20]
hello, thx for your great work @YangXu1990uiuc 

i am wondering if we can find a mapping relationship between the execution_engine with the original algorithm like CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD/CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM/CUDNN_CONVOLUTION_FWD_ALGO_IMPLICIT_​PRECOMP_GEMM.

**Comment by Anerudhan** [comment]
Hi @jackmsye ,

Thanks for your question.

The legacy algorithms consisted of one or more engines which would be run depending on the convolution problem. The engines comprising the algorithms are not disjoined sets and hence cannot be directly mapped to an algorithm. That being said one could query the `cudnnBackendNumericalNote_t ` to determine if the engine is `CUDNN_NUMERICAL_NOTE_WINOGRAD` / `CUDNN_NUMERICAL_NOTE_NONDETERMINISTIC`, etc. 

Let us know if you have further questions. 

Thanks

**Comment by Anerudhan** [comment]
Closing issue for now. 
Please reopen if needed,

Thanks,
Anerudhan
obo cuDNN Team
