### ISSUE TITLE
Why  implicit_convolveNd_hhgemm consume too long

### ISSUE THREAD

**Issue by xundaoxd** [NVIDIA/cudnn-frontend#22]
![Screenshot_20211222_152431](https://user-images.githubusercontent.com/36495505/147052309-b36885f1-ef70-42f6-af6a-97a116377e02.png)

it up to 7ms!!

**Comment by YangXu1990uiuc** [comment]
Hi @xundaoxd, can you provide more information about your system and setup, including GPU model, OS, cuda/cudnn version and the [API log](https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging) of the call that shows the problem?

**Comment by xundaoxd** [comment]
> he problem?

os: ubuntu:20.04
gpu: RTX3060
cuda: 11.4.2
cudnn: 8.2.4.15-1+cuda11.4

**Comment by xundaoxd** [comment]
> Hi @xundaoxd, thanks for reporting the issue! Can you provide more information about your system and setup, including GPU model, OS, cuda/cudnn version and the [API log](https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging) of the call that shows the problem?

os: ubuntu:20.04
gpu: RTX3060
cuda: 11.4.2
cudnn: 8.2.4.15-1+cuda11.4

**Comment by mnicely** [comment]
@xundaoxd has your issue been resolved?
