### ISSUE TITLE
Inference result of deep learning model is all NAN

### ISSUE THREAD

**Issue by akineeic** [NVIDIA/cudnn-frontend#23]
Hi,

I’m currently using CUDNN to write a deep learning super-resolution sample. But I found that the inference result of the model is all NAN. Then I tried to print the output of the middle layer and found that the output would be enlarged after one block, and the data exceeded the representation range after more than 20 blocks. As shown in the figure below.

![d59e9e23d3bfc17fe2ee0b01155d4df](https://user-images.githubusercontent.com/44738552/149283975-364c26b1-b5b1-491e-8eb6-a67844a74045.png)

But I compare it with the python version and confirmed that the input image and weight of convolutional layers are consistent.  So I think I made some mistakes while building the model using the CUDNN API. Could you please take a look at my [code](https://github.com/NVIDIA/cudnn-frontend/files/7860796/pipe.zip) to see if I made any obvious mistakes and give me some debugging suggestions? 

Thanks a lot in advance!

**Comment by YangXu1990uiuc** [comment]
Hi @akineeic I see you have commented out the line `cudnnSetStream(cudnn, my_stream);` is this intentional? Looks like cudnn handle's stream is not set properly so the kernel launch order may not be correct.

**Comment by akineeic** [comment]
Sorry for the later reply. I use `cudnnSetStream(cudnn, my_stream)` in file `pipe.cu`(see attached). Is that okay？
[pipe.zip](https://github.com/NVIDIA/cudnn-frontend/files/8034057/pipe.zip)

**Comment by mnicely** [comment]
@akineeic has your issues been resolved?

**Comment by mnicely** [comment]
We have refreshed our samples to support the newest frontend. You can find new examples [here](https://github.com/NVIDIA/cudnn-frontend/tree/main/samples). Closing this for now.
