### ISSUE TITLE
INT8 sample didn't work?

### ISSUE THREAD

**Issue by vincentccc** [NVIDIA/cudnn-frontend#31]
I tried cuda 11.2 ,11.4 and cudnn 8.1 , 8.2, 8.4, the Sample ConvScaleBiasAct_int8 didn't work in any combination of these env, and it will return the error :
"[ERROR] Exception CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED"
my device type is A100,  is there anything wrong?

**Comment by mnicely** [comment]
We have refreshed our samples to support the newest frontend. You can find new examples [here](https://github.com/NVIDIA/cudnn-frontend/tree/main/samples). Closing this for now.
