### ISSUE TITLE
Is dgrad+relu with fp32 supported?

### ISSUE THREAD

**Issue by tangjicheng46** [NVIDIA/cudnn-frontend#40]
I have try to fuse dgrad with some pointwise operation like relu,
but when cudnnBackendFinalize(plan), there is a error.
CUDNN_STATUS_NOT_SUPPORTED.

I am not sure if my code error.
I want know, is dgrad + pointwise support now in cudnn 8.6 for Turing Arch?
Could you give me some sample about dgrad fusion?
In this project, only one case for dgrad, but it it only support for Ampere Arch.

**Comment by tjich** [comment]
Here is my test code.

https://github.com/tjich/design_patterns/blob/main/lite_engine/cudnn_backend_api_test.cu

I try to fuse dgrad with some pointwise, but even fusion with only one relu operation is not ok.

**Comment by mnicely** [comment]
@tangjicheng46 has you resolved your issues?

**Comment by tangjicheng46** [comment]
> @tangjicheng46 has you resolved your issues?

I'm sorry, but I don't think I have solve this issue at that time. 
However, it's been a long time, and I'm not sure if this problem still exists.

**Comment by tangjicheng46** [comment]
> @tangjicheng46 has you resolved your issues?

I think we can just close this issue, 
I'm not following up on this issue right now.
