### ISSUE TITLE
question about the fusion_sample

### ISSUE THREAD

**Issue by cheneeheng** [NVIDIA/cudnn-frontend#42]
Hi there,

I am looking at the samples for convolution, and I came across 2 sample functions:  _run_conv_add_bias_activation_ and _run_conv_scale_bias_add_leaky_relu_ . Looking through the code, I noticed that both of them are identical except for the alignment value. 4 for the former and 16 for the latter.

My questions are:
1. Is there a reason for putting one in conv_sample and the other in fusion_sample?
2. Are there any differences besides the alignment value?
3. Did you set the alignment value to 16 "to run a tensor core engine", which in turn enables some sort of op fusion by cuda/cudnn? (Not a cuda coding expert here)

https://github.com/NVIDIA/cudnn-frontend/blob/8f488bd41229aa0a3d5f7c0168f59e4d69c618ee/samples/conv_sample.cpp#L539
https://github.com/NVIDIA/cudnn-frontend/blob/8f488bd41229aa0a3d5f7c0168f59e4d69c618ee/samples/fusion_sample.cpp#L86

Thanks!

**Comment by Anerudhan** [comment]
Hi @cheneeheng,

We were internally restructuring our code for better user experience. `conv_sample` was supposed to be convolution fusion and fusion sample for general fusions other than conv. 

Note that in 1.0 we have moved this to samples/cpp/*.cpp.


3. Did you set the alignment value to 16 "to run a tensor core engine", 
Yes. This is necessary to run tensor core engine which provides accelerated MMA operations.

Feel free to reopen the issue, if you have further questions.

Thanks
