### ISSUE TITLE
Update single header file for nlohmann json

### ISSUE THREAD

**Issue by ernestyalumni** [NVIDIA/cudnn-frontend#50]
nlohmann JSON is at 3.11 (major version 11) and consider updating that header file. Also, it will eliminate the need for compiling with C++11 features.

Be wary in that for the latest release of 3.11, the single header file tries to specialize a templatized value from std library outside its namespace. Which it shouldn't. I demonstrate a fix here: 

https://github.com/ernestyalumni/cudnn-frontend/commit/728a47488ac86498cf745f41e2ec0db981056af1

**Comment by Anerudhan** [comment]
Hi, 
Thanks for pointing this out.
 
We are updating the header file with our 1.0 GA release.  

The current pre-release [json.hpp ](https://github.com/NVIDIA/cudnn-frontend/blob/1.0/pre_release_4/include/thirdparty/nlohmann/json.hpp)  code have the updated version.

Please feel to reopen this issue if you think the issue has not been addressed.

**Comment by ernestyalumni** [comment]
@Anerudhan thank you for responding, I was worried it wouldn't be addressed. Let me also reproduce the issue on different environments and get back to you too.
