### ISSUE TITLE
Support use of external/system Catch2 installation

### ISSUE THREAD

**Issue by iskunk** [NVIDIA/cudnn-frontend#63]
I am building cudnn-frontend v1.1.0 in a restricted environment that is unable to use the FetchContent mechanism. I already have an existing build of Catch2 that should be consumed in its stead.

Elaborating the upper part of `samples/CMakeLists.txt` as follows will make this possible:
```
find_package(Catch2 QUIET)

if(NOT Catch2_FOUND)
    Include(FetchContent)

    # Fetch and build catch2
    FetchContent_Declare(
      Catch2
      GIT_REPOSITORY https://github.com/catchorg/Catch2.git
      GIT_TAG        v3.3.2
    )
    FetchContent_MakeAvailable(Catch2)
endif()
```
(I would submit this as a PR, but I see that PRs are not being accepted.)

I am then able to specify `-DCatch2_ROOT=/path/to/catch2-install` to CMake, and the samples build makes use of the existing library without issue.

**Comment by Anerudhan** [comment]
Hi @iskunk ,

Thanks for reporting this.  

Sure, we can add this to our upcoming release.  Thanks for the contribution.

Aside, we are also planning to open our FE repository to accept smaller PR such as these in near future. 

Will keep this issue open till the release is made.

Thanks,
Anerudhan obo cudnn team.
