### ISSUE TITLE
Support "make install"

### ISSUE THREAD

**Issue by iskunk** [NVIDIA/cudnn-frontend#64]
Even though the cudnn-frontend library is header-only, and effectively consists of just the files under `include/`, the lack of a CMake `install` target to populate an installation location is not conventional.

Adding the following to the top-level `CMakeLists.txt` will provide the minimum expected behavior:
```
include(GNUInstallDirs)

install(DIRECTORY include/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
)
```

Additional files (e.g. documentation under `${CMAKE_INSTALL_PREFIX}/share/doc/cudnn-frontend/`) may be added as appropriate.

**Comment by mnicely** [comment]
Added to v1.2
