### ISSUE TITLE
identifier "geomlib::_NV_ANON_NAMESPACE::kEps" is undefined in device code

### ISSUE THREAD

**Issue by zcc2xj** [NVIDIA/cudnn-frontend#67]
VS 2019(16.11.34):cmake(3.20.21032501-MSVC_2)
cuda(10.2)
cudnn(9.0+10.2)
libtorch(1.10.1+cuda 10.2)
VulkanSDK-1.3.275.0
hdf5-1.14.3
CMAKE the project is ok
but when I use the PolycubeHexMesher.sln and generate it shows:
identifier "geomlib::_NV_ANON_NAMESPACE::kEps" is undefined in device code
(in the file "generalized_projection_cuda.cu", there are several error)

**Comment by zcc2xj** [comment]
Win7 x64 OS, so there is no cuda above 10.2 for my Quadro K2200 GPU

**Comment by Anerudhan** [comment]
Hi @zcc2xj , thanks for reporting this.

This does not look like cudnn_frontend issue. Can you post it in the cudnn forums.

[https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/cudnn/90](https://forums.developer.nvidia.com/c/ai-data-science/deep-learning/cudnn/90).

Please reopen the issue, if anything is required.
