### ISSUE TITLE
[ERROR] Exception CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Tr-buaa** [NVIDIA/cudnn-frontend#71]
Hello，I have met some questions that I cannot run the testcase `bin/samples [fusion]`,the error messages are below:

```
bin/samples [fusion]
Filters: [fusion]
Randomness seeded to: 415973869
TEST_CASE :: ConvScaleBiasAddAct sample
====DIMENSIONS====
input dims are 4, 24, 31, 31
filter dims are 32, 24, 3, 3
output dims are 4, 32, 31, 31
[ERROR] Exception CUDNN_BACKEND_TENSOR_DESCRIPTOR cudnnFinalize failed cudnn_status: CUDNN_STATUS_NOT_INITIALIZED

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
samples is a Catch2 v3.5.3 host application.
Run with -? for options

-------------------------------------------------------------------------------
ConvScaleBiasAddAct sample
-------------------------------------------------------------------------------
/home/tairan/work/cuda/cudnn-frontend/samples/legacy_samples/test_list.cpp:705
...............................................................................

/home/tairan/work/cuda/cudnn-frontend/samples/legacy_samples/fusion_sample.cpp:347: FAILED:
  CHECK( false )
with message:
  TEST_CASE :: ConvScaleBiasAddAct sample
```

cuda version:12.2  
driver version:535.129.03
cudnn version:9

Other hand, when I compile the project with cmake, it give me some messages as below:

```
Warning: Unused direct dependencies:
        /usr/local/cuda-12.2/lib64/libnvrtc.so.12
        /lib/x86_64-linux-gnu/libcuda.so.1
        /usr/local/cuda-12.2/lib64/libcudnn_adv.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_ops.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_cnn.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_graph.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_engines_runtime_compiled.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_engines_precompiled.so.9
        /usr/local/cuda-12.2/lib64/libcudnn_heuristic.so.9
```

Maybe the question from here? I can run normal cudnn code such as mnist, so I think it doesn't the compatibility problem between CUDA and cudnn.

**Comment by Anerudhan** [comment]
Hi @Tr-buaa, thanks for posting this.

Few questions:

- Can you post the cudnn log with environment variable `CUDNN_LOGLEVEL_DBG=3`.

- Do you have another installation of cudnn in your system?

- Can you try setting the LD_LIBRARY_PATH to /usr/local/cuda-12.2/lib64/ and trying?

Thanks
Anerudhan

**Comment by Tr-buaa** [comment]
> Hi @Tr-buaa, thanks for posting this.
> 
> Few questions:
> 
> * Can you post the cudnn log with environment variable `CUDNN_LOGLEVEL_DBG=3`.
> * Do you have another installation of cudnn in your system?
> * Can you try setting the LD_LIBRARY_PATH to /usr/local/cuda-12.2/lib64/ and trying?
> 
> Thanks Anerudhan

  Oh, thank you, I have found the questions, when I installed cudnn, I simply copy the libcudnn* to the `/usr/local/cuda-12.2/lib64`, and ignore the symlink，it cause the libcudnn*.so in `/usr/local/cuda-12.2/lib64`  not symlink.
  So I recopy it with symlink, then solve this problem, it can successfully load the .so.9 library and run test passed!
