### ISSUE TITLE
Default `cudnnConvolutionMode_t` and how to set it?

### ISSUE THREAD

**Issue by ogoidmatos** [NVIDIA/cudnn-frontend#82]
Hello,

I've been reading through the documentation, especially regarding the convolution operation and I'm confused on what is the default mode for the convolution operation, whether it is `CUDNN_CONVOLUTION` or `CUDNN_CROSS_CORRELATION`. I would appreciate it if someone could clarify this question, and additionally, I would like to ask if currently there is a setter to change between operation modes.

Thank you!

**Comment by Anerudhan** [comment]
Default convolution mode is `CUDNN_CONVOLUTION`
https://github.com/NVIDIA/cudnn-frontend/blob/main/include/cudnn_frontend_ConvDesc.h#L149

**Comment by ogoidmatos** [comment]
That feels contradictory with the descriptor built here: https://github.com/NVIDIA/cudnn-frontend/blob/019bab67ed175ed8dca6db217f8bdaad457c13bc/include/cudnn_frontend/node/conv_fprop.h#L111
And additionally, is there a way to access this setter from the provided interface?

**Comment by Anerudhan** [comment]
Thanks for the comment. I have added the setter in  [branch](https://github.com/NVIDIA/cudnn-frontend/tree/1.6.0-rc). Will merge to main shortly.
