### ISSUE TITLE
Question about calling MHA

### ISSUE THREAD

**Issue by GonChen** [NVIDIA/cudnn-frontend#85]
Hi,

cuDNN also features MHA and delivers excellent performance. But, it
need to construct a big graph from C-API to get the MHA engine. I think it maybe a little complex and easy causes mistake. Although using front-end api maybe better, but constructing a big graph also may cost CPU a lot. Why not just add an MHA Operation Descriptor?

reference:
https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/legacy_samples/f16_flash_mha_sample.cpp

**Comment by Anerudhan** [comment]
Hi @GonChen,

Thanks for the question.

There are several variations of the sdpa (masking, biases) that makes it tricky to support as a single backend descriptor.

I also noticed that you are looking at the legacy_sample which is a bit verbose.  I would suggest looking [here](https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/cpp/sdpa/fp16_fwd.cpp#L119). 

Regarding high construction cost of graph, I would suggest caching it as shown in [this](https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/cpp/sdpa/fp16_cached.cpp) example.

Thanks

**Comment by GonChen** [comment]
> Hi @GonChen,
> 
> Thanks for the question.
> 
> There are several variations of the sdpa (masking, biases) that makes it tricky to support as a single backend descriptor.
> 
> I also noticed that you are looking at the legacy_sample which is a bit verbose. I would suggest looking [here](https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/cpp/sdpa/fp16_fwd.cpp#L119).
> 
> Regarding high construction cost of graph, I would suggest caching it as shown in [this](https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/cpp/sdpa/fp16_cached.cpp) example.
> 
> Thanks

@Anerudhan  Thanks for your replay. It is almost resolve my question. I can close the issue now.
