### ISSUE TITLE
[Question] Should I be creating the graph everytime?

### ISSUE THREAD

**Issue by vedantroy** [NVIDIA/cudnn-frontend#91]
As shown here: https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/python/50_scaled_dot_product_attention.ipynb, we create a graph, validate it, etc. etc.

Should we be doing this everytime we do a forward / backward pass, or should it be created once and re-used for different inputs / outputs.

Furthermore, is there an alternative to `tensor_like` that doesn't require a tensor, but instead takes in a shape?

**Comment by vedaanta** [comment]
There is a graph.tensor():
https://github.com/NVIDIA/cudnn-frontend/blob/main/python/cudnn/__init__.py#L31-L40

Example usage: https://github.com/NVIDIA/cudnn-frontend/blob/main/test/python_fe/test_conv_bias.py#L68-L70

**Comment by vedaanta** [comment]
Building a graph once and running multiple times is the general usecase actually.
In the spda notebook, you can keeping changing the variant pack tensor to run with different i/o tensors:

```
variant_pack = {
    q: q_gpu_0,
    k: k_gpu_0,
    v: v_gpu_0,
    o: o_gpu_0,
}
graph.execute(variant_pack, workspace)

variant_pack = {
    q: q_gpu_1,
    k: k_gpu_1,
    v: v_gpu_1,
    o: o_gpu_1,
}
graph.execute(variant_pack, workspace)

```

**Comment by vedantroy** [comment]
For running the forward / backward pass in Pytorch when training a model -- do I need to wrap the graph code in an autograd function. (I'm aware Pytorch probably already uses cuDNN, but it doesn't seem to support certain things like `varlen`).
