### ISSUE TITLE
[Question] Why are the physical and logical layouts different in the SDPA example?

### ISSUE THREAD

**Issue by vedantroy** [NVIDIA/cudnn-frontend#94]
In the SDPA example, the tensors have different physical and logical layouts: https://github.com/NVIDIA/cudnn-frontend/blob/main/samples/python/50_scaled_dot_product_attention.ipynb.

The documentation indicates the dimensions should be BHSD: https://github.com/NVIDIA/cudnn-frontend/blob/main/docs/operations/Attention.md#scaled-dot-product-attention, so I'm wondering why bother using a different physical layout?

**Comment by vedantroy** [comment]
Also ... I'm wondering, when should I be setting `use_padding_mask` to `True` or `False`. I'm already using `seq_len_q` and `seq_len_kv`.

**Comment by Anerudhan** [comment]
The dimensions of the tensor should always be `B,H,S,D`. However, the physical layout can differ depending on the actual tensor (interleaved/non-interleaved). 
Some layout are mentioned [here ](https://github.com/NVIDIA/cudnn-frontend/blob/main/test/python_fe/test_mhas.py#L194)
